/* _GlobalPrefix_ */
"use strict";this.default_host=this.default_host||{};(function(_){var window=this;
/* _Module_:ultraviolet_base_module */
try{
_.aa=_.aa||{};_.k=this;_.ba="closure_uid_"+(1E9*Math.random()>>>0);_.m=Date.now||function(){return+new Date};
}catch(e){_._DumpException(e)}
/* _Module_:sy0 */
try{
var la,ma;_.p=function(a){return void 0!==a};_.q=function(a){return"string"==typeof a};_.ca=function(a){return"number"==typeof a};_.da=function(a){a=a.split(".");for(var b=_.k,c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b};_.ea=function(){};
_.fa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.ha=function(a){return"array"==_.fa(a)};_.ia=function(a){var b=_.fa(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.ja=function(a){return"function"==_.fa(a)};_.ka=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};la=function(a,b,c){return a.call.apply(a.bind,arguments)};
ma=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};_.t=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?_.t=la:_.t=ma;return _.t.apply(null,arguments)};
_.na=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.oa=function(a,b){a=a.split(".");var c=_.k;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&_.p(b)?c[d]=b:c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}};
_.u=function(a,b){function c(){}c.prototype=b.prototype;a.w=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Tc=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};
_.pa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.pa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.u(_.pa,Error);_.pa.prototype.name="CustomError";var qa;qa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(_.q(a))return _.q(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.v=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.q(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.sa=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f=_.q(a)?a.split(""):a,h=0;h<c;h++)if(h in f){var l=f[h];b.call(void 0,l,h,a)&&(d[e++]=l)}return d};_.ta=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e=_.q(a)?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d};
_.ua=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.q(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.wa=function(a,b){b=_.va(a,b,void 0);return 0>b?null:_.q(a)?a.charAt(b):a[b]};_.va=function(a,b,c){for(var d=a.length,e=_.q(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};_.xa=function(a,b){return 0<=qa(a,b)};_.za=function(a,b){b=qa(a,b);var c;(c=0<=b)&&_.ya(a,b);return c}; _.ya=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};_.Aa=function(a){return Array.prototype.concat.apply([],arguments)};_.Ba=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
var Ga,Ia;_.Ca=function(a,b){return 0==a.lastIndexOf(b,0)};_.Da=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};_.Ea=function(a){return/^[\s\xa0]*$/.test(a)};_.Fa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};Ga=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};_.Ha=function(a){return null==a?"":String(a)};
_.Ja=function(a,b){var c=0;a=(0,_.Fa)(String(a)).split(".");b=(0,_.Fa)(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;0==c&&e<d;e++){var f=a[e]||"",h=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==f[0].length&&0==h[0].length)break;c=Ia(0==f[1].length?0:(0,window.parseInt)(f[1],10),0==h[1].length?0:(0,window.parseInt)(h[1],10))||Ia(0==f[2].length,0==h[2].length)||Ia(f[2],h[2]);f=f[3];h=h[3]}while(0==c)}return c}; Ia=function(a,b){return a<b?-1:a>b?1:0};
a:{var La=_.k.navigator;if(La){var Ma=La.userAgent;if(Ma){_.Ka=Ma;break a}}_.Ka=""}_.x=function(a){return-1!=_.Ka.indexOf(a)};var Oa,Qa;_.Na=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Oa=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};_.Pa=function(a){var b={},c;for(c in a)b[c]=a[c];return b};Qa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");_.Ra=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Qa.length;f++)c=Qa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
var Sa=function(){return(_.x("Chrome")||_.x("CriOS"))&&!_.x("Edge")};var Ta,Ua;Ta=function(){return _.x("iPhone")&&!_.x("iPod")&&!_.x("iPad")};Ua=function(){return Ta()||_.x("iPad")||_.x("iPod")};_.Va=function(){return _.x("Macintosh")};_.Wa=function(){return _.x("Windows")};_.Xa=function(){return _.x("CrOS")};var Ya=function(a){Ya[" "](a);return a};Ya[" "]=_.ea;_.Za=function(a,b){try{return Ya(a[b]),!0}catch(c){}return!1};_.$a=function(a,b,c){return Object.prototype.hasOwnProperty.call(a,b)?a[b]:a[b]=c(b)};var ab,cb,gb,jb,kb,ob,pb,rb;ab=_.x("Opera");_.bb=_.x("Trident")||_.x("MSIE");cb=_.x("Edge");_.db=_.x("Gecko")&&!(-1!=_.Ka.toLowerCase().indexOf("webkit")&&!_.x("Edge"))&&!(_.x("Trident")||_.x("MSIE"))&&!_.x("Edge");_.eb=-1!=_.Ka.toLowerCase().indexOf("webkit")&&!_.x("Edge");gb=_.k.navigator||null;_.fb=gb&&gb.platform||"";_.hb=_.Va();_.ib=_.Wa();jb=function(){var a=_.k.document;return a?a.documentMode:void 0};
a:{var lb="",mb=function(){var a=_.Ka;if(_.db)return/rv:([^\);]+)(\)|;)/.exec(a);if(cb)return/Edge\/([\d\.]+)/.exec(a);if(_.bb)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.eb)return/WebKit\/(\S+)/.exec(a);if(ab)return/(?:Version)[ \/]?(\S+)/.exec(a)}();mb&&(lb=mb?mb[1]:"");if(_.bb){var nb=jb();if(null!=nb&&nb>(0,window.parseFloat)(lb)){kb=String(nb);break a}}kb=lb}ob=kb;pb={};_.qb=function(a){return _.$a(pb,a,function(){return 0<=_.Ja(ob,a)})};var sb=_.k.document; rb=sb&&_.bb?jb()||("CSS1Compat"==sb.compatMode?(0,window.parseInt)(ob,10):5):void 0;
var tb=_.x("Firefox"),ub=Ta()||_.x("iPod"),vb=_.x("iPad"),wb=_.x("Android")&&!(Sa()||_.x("Firefox")||_.x("Opera")||_.x("Silk")),xb=Sa(),yb=_.x("Safari")&&!(Sa()||_.x("Coast")||_.x("Opera")||_.x("Edge")||_.x("Silk")||_.x("Android"))&&!Ua();var zb=null;var Cb,Eb;_.y=function(){};_.Ab="function"==typeof window.Uint8Array;
_.B=function(a,b,c,d,e){a.a=null;b||(b=c?[c]:[]);a.l=c?String(c):void 0;a.c=0===c?-1:0;a.b=b;a:{if(a.b.length&&(b=a.b.length-1,(c=a.b[b])&&"object"==typeof c&&!_.ha(c)&&!(_.Ab&&c instanceof window.Uint8Array))){a.h=b-a.c;a.g=c;break a}a.h=Number.MAX_VALUE}a.j={};if(d)for(b=0;b<d.length;b++)c=d[b],c<a.h?(c+=a.c,a.b[c]=a.b[c]||_.Bb):(Cb(a),a.g[c]=a.g[c]||_.Bb);if(e&&e.length)for(b=0;b<e.length;b++){c=d=void 0;for(var f=a,h=e[b],l=0;l<h.length;l++){var n=h[l],r=_.z(f,n);null!=r&&(c=n,d=r,_.A(f,n,void 0))}c&&
_.A(f,c,d)}};_.Bb=[];Cb=function(a){var b=a.h+a.c;a.b[b]||(a.g=a.b[b]={})};_.z=function(a,b){if(b<a.h){b+=a.c;var c=a.b[b];return c===_.Bb?a.b[b]=[]:c}if(a.g)return c=a.g[b],c===_.Bb?a.g[b]=[]:c};_.Db=function(a,b,c){a=_.z(a,b);return null==a?c:a};_.A=function(a,b,c){b<a.h?a.b[b+a.c]=c:(Cb(a),a.g[b]=c)};_.C=function(a,b,c){a.a||(a.a={});if(!a.a[c]){var d=_.z(a,c);d&&(a.a[c]=new b(d))}return a.a[c]};_.E=function(a,b,c){a.a||(a.a={});var d=c?_.D(c):c;a.a[b]=c;_.A(a,b,d)};
Eb=function(a){if(a.a)for(var b in a.a){var c=a.a[b];if(_.ha(c))for(var d=0;d<c.length;d++)c[d]&&_.D(c[d]);else c&&_.D(c)}};_.D=function(a){Eb(a);return a.b};
_.y.prototype.C=_.Ab?function(){var a=window.Uint8Array.prototype.toJSON;window.Uint8Array.prototype.toJSON=function(){if(!zb){zb={};for(var a=0;65>a;a++)zb[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)}a=zb;for(var c=[],d=0;d<this.length;d+=3){var e=this[d],f=d+1<this.length,h=f?this[d+1]:0,l=d+2<this.length,n=l?this[d+2]:0,r=e>>2;e=(e&3)<<4|h>>4;h=(h&15)<<2|n>>6;n&=63;l||(n=64,f||(h=64));c.push(a[r],a[e],a[h],a[n])}return c.join("")};try{return JSON.stringify(this.b&&
_.D(this),Fb)}finally{window.Uint8Array.prototype.toJSON=a}}:function(){return JSON.stringify(this.b&&_.D(this),Fb)};var Fb=function(a,b){return _.ca(b)&&((0,window.isNaN)(b)||window.Infinity===b||-window.Infinity===b)?String(b):b};_.y.prototype.toString=function(){Eb(this);return this.b.toString()};
_.F=function(){this.G=this.G;this.C=this.C};_.F.prototype.G=!1;_.F.prototype.$=function(){this.G||(this.G=!0,this.v())};_.I=function(a,b){_.G(a,_.na(_.H,b))};_.G=function(a,b,c){a.G?_.p(c)?b.call(c):b():(a.C||(a.C=[]),a.C.push(_.p(c)?(0,_.t)(b,c):b))};_.F.prototype.v=function(){if(this.C)for(;this.C.length;)this.C.shift()()};_.H=function(a){a&&"function"==typeof a.$&&a.$()};
var Gb=function(a,b){this.g=a;this.c=b;this.b=0;this.a=null};Gb.prototype.get=function(){if(0<this.b){this.b--;var a=this.a;this.a=a.next;a.next=null}else a=this.g();return a};var Hb=function(a,b){a.c(b);100>a.b&&(a.b++,b.next=a.a,a.a=b)};var Lb;_.Ib=[];_.Jb=[];_.Kb=!1;Lb=function(a){_.Ib[_.Ib.length]=a;if(_.Kb)for(var b=0;b<_.Jb.length;b++)a((0,_.t)(_.Jb[b].b,_.Jb[b]))};_.Mb=function(a){return function(){return a}}(!1);var Nb,Pb,Qb,Ob;Nb=function(a){_.k.setTimeout(function(){throw a;},0)};_.Rb=function(a,b){var c=a;b&&(c=(0,_.t)(a,b));c=Ob(c);!_.ja(_.k.setImmediate)||_.k.Window&&_.k.Window.prototype&&!_.x("Edge")&&_.k.Window.prototype.setImmediate==_.k.setImmediate?(Pb||(Pb=Qb()),Pb(c)):_.k.setImmediate(c)};
Qb=function(){var a=_.k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.x("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow;a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host;a=(0,_.t)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.x("Trident")&&!_.x("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.p(c.next)){c=c.next;var a=c.wb;c.wb=null;a()}};return function(a){d.next={wb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=
window.document.createElement("SCRIPT");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.k.setTimeout(a,0)}};Ob=function(a){return a};Lb(function(a){Ob=a});
var Sb=function(){this.b=this.a=null},Ub=new Gb(function(){return new Tb},function(a){a.reset()});Sb.prototype.add=function(a,b){var c=Ub.get();c.set(a,b);this.b?this.b.next=c:this.a=c;this.b=c};Sb.prototype.remove=function(){var a=null;this.a&&(a=this.a,this.a=this.a.next,this.a||(this.b=null),a.next=null);return a};var Tb=function(){this.next=this.b=this.a=null};Tb.prototype.set=function(a,b){this.a=a;this.b=b;this.next=null};Tb.prototype.reset=function(){this.next=this.b=this.a=null};
var Zb=function(a,b){Vb||Wb();Xb||(Vb(),Xb=!0);Yb.add(a,b)},Vb,Wb=function(){if(-1!=String(_.k.Promise).indexOf("[native code]")){var a=_.k.Promise.resolve(void 0);Vb=function(){a.then($b)}}else Vb=function(){_.Rb($b)}},Xb=!1,Yb=new Sb,$b=function(){for(var a;a=Yb.remove();){try{a.a.call(a.b)}catch(b){Nb(b)}Hb(Ub,a)}Xb=!1};
var ac=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},bc=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var ec,fc,gc,lc,pc,qc,oc,mc;_.dc=function(a,b){this.a=0;this.j=void 0;this.c=this.b=this.g=null;this.h=this.C=!1;if(a!=_.ea)try{var c=this;a.call(b,function(a){_.cc(c,2,a)},function(a){_.cc(c,3,a)})}catch(d){_.cc(this,3,d)}};ec=function(){this.next=this.c=this.b=this.h=this.a=null;this.g=!1};ec.prototype.reset=function(){this.c=this.b=this.h=this.a=null;this.g=!1};fc=new Gb(function(){return new ec},function(a){a.reset()});gc=function(a,b,c){var d=fc.get();d.h=a;d.b=b;d.c=c;return d};
_.ic=function(){var a,b=new _.dc(function(b){a=b});return new hc(b,a)};_.dc.prototype.then=function(a,b,c){return _.jc(this,_.ja(a)?a:null,_.ja(b)?b:null,c)};ac(_.dc);_.dc.prototype.cancel=function(a){0==this.a&&Zb(function(){var b=new kc(a);lc(this,b)},this)};
lc=function(a,b){if(0==a.a)if(a.g){var c=a.g;if(c.b){for(var d=0,e=null,f=null,h=c.b;h&&(h.g||(d++,h.a==a&&(e=h),!(e&&1<d)));h=h.next)e||(f=h);e&&(0==c.a&&1==d?lc(c,b):(f?(d=f,d.next==c.c&&(c.c=d),d.next=d.next.next):mc(c),nc(c,e,3,b)))}a.g=null}else _.cc(a,3,b)};pc=function(a,b){a.b||2!=a.a&&3!=a.a||oc(a);a.c?a.c.next=b:a.b=b;a.c=b};
_.jc=function(a,b,c,d){var e=gc(null,null,null);e.a=new _.dc(function(a,h){e.h=b?function(c){try{var e=b.call(d,c);a(e)}catch(r){h(r)}}:a;e.b=c?function(b){try{var e=c.call(d,b);!_.p(e)&&b instanceof kc?h(b):a(e)}catch(r){h(r)}}:h});e.a.g=a;pc(a,e);return e.a};_.dc.prototype.m=function(a){this.a=0;_.cc(this,2,a)};_.dc.prototype.o=function(a){this.a=0;_.cc(this,3,a)};
_.cc=function(a,b,c){if(0==a.a){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.a=1;a:{var d=c,e=a.m,f=a.o;if(d instanceof _.dc){pc(d,gc(e||_.ea,f||null,a));var h=!0}else if(bc(d))d.then(e,f,a),h=!0;else{if(_.ka(d))try{var l=d.then;if(_.ja(l)){qc(d,l,e,f,a);h=!0;break a}}catch(n){f.call(a,n);h=!0;break a}h=!1}}h||(a.j=c,a.a=b,a.g=null,oc(a),3!=b||c instanceof kc||rc(a,c))}};
qc=function(a,b,c,d,e){var f=!1,h=function(a){f||(f=!0,c.call(e,a))},l=function(a){f||(f=!0,d.call(e,a))};try{b.call(a,h,l)}catch(n){l(n)}};oc=function(a){a.C||(a.C=!0,Zb(a.l,a))};mc=function(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.c=null);return b};_.dc.prototype.l=function(){for(var a;a=mc(this);)nc(this,a,this.a,this.j);this.C=!1};
var nc=function(a,b,c,d){if(3==c&&b.b&&!b.g)for(;a&&a.h;a=a.g)a.h=!1;if(b.a)b.a.g=null,sc(b,c,d);else try{b.g?b.h.call(b.c):sc(b,c,d)}catch(e){tc.call(null,e)}Hb(fc,b)},sc=function(a,b,c){2==b?a.h.call(a.c,c):a.b&&a.b.call(a.c,c)},rc=function(a,b){a.h=!0;Zb(function(){a.h&&tc.call(null,b)})},tc=Nb,kc=function(a){_.pa.call(this,a)};_.u(kc,_.pa);kc.prototype.name="cancel";var hc=function(a,b){this.a=a;this.b=b};
/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.uc=function(a,b){this.j=[];this.D=a;this.I=b||null;this.h=this.la=!1;this.c=void 0;this.o=this.M=this.m=!1;this.l=0;this.a=null;this.C=0};_.uc.prototype.cancel=function(a){if(this.la)this.c instanceof _.uc&&this.c.cancel();else{if(this.a){var b=this.a;delete this.a;a?b.cancel(a):(b.C--,0>=b.C&&b.cancel())}this.D?this.D.call(this.I,this):this.o=!0;this.la||this.A(new _.vc(this))}};_.uc.prototype.F=function(a,b){this.m=!1;wc(this,a,b)};
var wc=function(a,b,c){a.la=!0;a.c=c;a.h=!b;xc(a)},zc=function(a){if(a.la){if(!a.o)throw new yc(a);a.o=!1}};_.uc.prototype.g=function(a){zc(this);wc(this,!0,a)};_.uc.prototype.A=function(a){zc(this);wc(this,!1,a)};_.Bc=function(a,b,c){_.Ac(a,b,null,c)};_.Ac=function(a,b,c,d){a.j.push([b,c,d]);a.la&&xc(a)};_.uc.prototype.then=function(a,b,c){var d,e,f=new _.dc(function(a,b){d=a;e=b});_.Ac(this,d,function(a){a instanceof _.vc?f.cancel():e(a)});return f.then(a,b,c)};ac(_.uc);
_.uc.prototype.b=function(a){var b=new _.uc;_.Ac(this,b.g,b.A,b);a&&(b.a=this,this.C++);return b};_.uc.prototype.isError=function(a){return a instanceof Error};
var Cc=function(a){return(0,_.ua)(a.j,function(a){return _.ja(a[1])})},xc=function(a){if(a.l&&a.la&&Cc(a)){var b=a.l,c=Dc[b];c&&(_.k.clearTimeout(c.a),delete Dc[b]);a.l=0}a.a&&(a.a.C--,delete a.a);b=a.c;for(var d=c=!1;a.j.length&&!a.m;){var e=a.j.shift(),f=e[0],h=e[1];e=e[2];if(f=a.h?h:f)try{var l=f.call(e||a.I,b);_.p(l)&&(a.h=a.h&&(l==b||a.isError(l)),a.c=b=l);if(bc(b)||"function"===typeof _.k.Promise&&b instanceof _.k.Promise)d=!0,a.m=!0}catch(n){b=n,a.h=!0,Cc(a)||(c=!0)}}a.c=b;d&&(l=(0,_.t)(a.F,
a,!0),d=(0,_.t)(a.F,a,!1),b instanceof _.uc?(_.Ac(b,l,d),b.M=!0):b.then(l,d));c&&(b=new Ec(b),Dc[b.a]=b,a.l=b.a)},yc=function(){_.pa.call(this)};_.u(yc,_.pa);yc.prototype.message="Deferred has already fired";yc.prototype.name="AlreadyCalledError";_.vc=function(){_.pa.call(this)};_.u(_.vc,_.pa);_.vc.prototype.message="Deferred was canceled";_.vc.prototype.name="CanceledError";var Ec=function(a){this.a=_.k.setTimeout((0,_.t)(this.g,this),0);this.b=a}; Ec.prototype.g=function(){delete Dc[this.a];throw this.b;};var Dc={};
var Fc=!_.db&&!_.bb||_.bb&&9<=Number(rb)||_.db&&_.qb("1.9.1");_.Gc=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;_.Ic=function(){this.a="";this.b=_.Hc};_.Ic.prototype.Fa=!0;_.Ic.prototype.Ca=function(){return this.a};_.Ic.prototype.nb=!0;_.Ic.prototype.Ra=function(){return 1};_.Hc={};_.Jc=function(a){var b=new _.Ic;b.a=a;return b};_.Jc("about:blank");_.Lc=function(){this.a="";this.g=_.Kc;this.b=null};_.Lc.prototype.nb=!0;_.Lc.prototype.Ra=function(){return this.b};_.Lc.prototype.Fa=!0;_.Lc.prototype.Ca=function(){return this.a};_.Kc={};_.Mc=function(a,b){var c=new _.Lc;c.a=a;c.b=b;return c};_.Mc("<!DOCTYPE html>",0);_.Mc("",0);_.Nc=_.Mc("<br>",0);
var Qc;_.Pc=function(a,b){var c=b||window.document;if(c.getElementsByClassName)a=c.getElementsByClassName(a)[0];else{c=window.document;var d=b||c;a=d.querySelectorAll&&d.querySelector&&a?d.querySelector(a?"."+a:""):_.Oc(c,"*",a,b)[0]||null}return a||null};
_.Oc=function(a,b,c,d){a=d||a;b=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,h;h=a[f];f++)b==h.nodeName&&(d[e++]=h);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;h=a[f];f++)b=h.className,"function"==typeof b.split&&_.xa(b.split(/\s+/),c)&&(d[e++]=h);d.length=e;return d}return a};
_.Rc=function(a,b){_.Na(b,function(b,d){b&&b.Fa&&(b=b.Ca());"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Qc.hasOwnProperty(d)?a.setAttribute(Qc[d],b):_.Ca(d,"aria-")||_.Ca(d,"data-")?a.setAttribute(d,b):a[d]=b})};Qc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
_.Sc=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.Tc=function(a){this.a=a||_.k.document||window.document};_.Tc.prototype.B=function(a){return _.q(a)?this.a.getElementById(a):a};_.Tc.prototype.setProperties=_.Rc;_.Uc=function(a,b){return a.a.createElement(String(b))};_.Tc.prototype.getChildren=function(a){return Fc&&void 0!=a.children?a.children:(0,_.sa)(a.childNodes,function(a){return 1==a.nodeType})};
_.Tc.prototype.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};
var Wc,Vc,Zc,$c,Yc;_.Xc=function(a){var b=[];Vc(new Wc,a,b);return b.join("")};Wc=function(){};
Vc=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(_.ha(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),Vc(a,d[f],c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(f=b[d],"function"!=typeof f&&(c.push(e),Yc(d,c),c.push(":"),Vc(a,f,c),e=","));c.push("}");return}}switch(typeof b){case "string":Yc(b,c);break;case "number":c.push((0,window.isFinite)(b)&&
!(0,window.isNaN)(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("d`"+typeof b);}}};Zc={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};$c=/\uffff/.test("\uffff")?/[\\"\x00-\x1f\x7f-\uffff]/g:/[\\"\x00-\x1f\x7f-\xff]/g;Yc=function(a,b){b.push('"',a.replace($c,function(a){var b=Zc[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),Zc[a]=b);return b}),'"')};
var ad="StopIteration"in _.k?_.k.StopIteration:{message:"StopIteration",stack:""},bd=function(){};bd.prototype.next=function(){throw ad;};bd.prototype.ia=function(){return this};
var cd=function(a){if(a instanceof bd)return a;if("function"==typeof a.ia)return a.ia(!1);if(_.ia(a)){var b=0,c=new bd;c.next=function(){for(;;){if(b>=a.length)throw ad;if(b in a)return a[b++];b++}};return c}throw Error("e");},dd=function(a,b){if(_.ia(a))try{(0,_.v)(a,b,void 0)}catch(c){if(c!==ad)throw c;}else{a=cd(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(c){if(c!==ad)throw c;}}},ed=function(a){if(_.ia(a))return _.Ba(a);a=cd(a);var b=[];dd(a,function(a){b.push(a)});return b};
_.J=function(a,b){this.b={};this.a=[];this.c=this.g=0;var c=arguments.length;if(1<c){if(c%2)throw Error("b");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof _.J)for(c=a.X(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])};_.J.prototype.T=function(){fd(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};_.J.prototype.X=function(){fd(this);return this.a.concat()};_.hd=function(a,b){return gd(a.b,b)};
_.J.prototype.clear=function(){this.b={};this.c=this.g=this.a.length=0};_.J.prototype.remove=function(a){return gd(this.b,a)?(delete this.b[a],this.g--,this.c++,this.a.length>2*this.g&&fd(this),!0):!1};var fd=function(a){if(a.g!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];gd(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.g!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],gd(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};_.J.prototype.get=function(a,b){return gd(this.b,a)?this.b[a]:b};
_.J.prototype.set=function(a,b){gd(this.b,a)||(this.g++,this.a.push(a),this.c++);this.b[a]=b};_.J.prototype.forEach=function(a,b){for(var c=this.X(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};_.J.prototype.ia=function(a){fd(this);var b=0,c=this.c,d=this,e=new bd;e.next=function(){if(c!=d.c)throw Error("f");if(b>=d.a.length)throw ad;var e=d.a[b++];return a?e:d.b[e]};return e};var gd=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
_.K=function(a,b){this.type="undefined"!=typeof _.id&&a instanceof _.id?String(a):a;this.b=this.target=b;this.c=!1;this.Bb=!0};_.K.prototype.h=function(){this.c=!0};_.K.prototype.g=function(){this.Bb=!1};var jd=!_.bb||9<=Number(rb),kd=_.bb&&!_.qb("9"),ld=function(){if(!_.k.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});_.k.addEventListener("test",_.ea,b);_.k.removeEventListener("test",_.ea,b);return a}();
var nd=function(a,b){_.K.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;(b=a.relatedTarget)?_.db&&(_.Za(b,"nodeName")||(b=null)):"mouseover"==c?b=a.fromElement:"mouseout"==
c&&(b=a.toElement);this.relatedTarget=b;null===d?(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0):(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=
a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=_.q(a.pointerType)?a.pointerType:md[a.pointerType]||"";this.a=a;a.defaultPrevented&&this.g()}};_.u(nd,_.K);var md={2:"touch",3:"pen",4:"mouse"};nd.prototype.h=function(){nd.w.h.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};nd.prototype.g=function(){nd.w.g.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,kd)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var od,qd;od="closure_listenable_"+(1E6*Math.random()|0);_.pd=function(a){return!(!a||!a[od])};qd=0;var rd=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.Sa=e;this.key=++qd;this.removed=this.Pa=!1},sd=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.Sa=null};var td=function(a){this.src=a;this.a={};this.b=0},xd,ud;td.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var h=ud(a,b,d,e);-1<h?(b=a[h],c||(b.Pa=!1)):(b=new rd(b,this.src,f,!!d,e),b.Pa=c,a.push(b));return b};td.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=ud(e,b,c,d);return-1<b?(sd(e[b]),_.ya(e,b),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var vd=function(a,b){var c=b.type;c in a.a&&_.za(a.a[c],b)&&(sd(b),0==a.a[c].length&&(delete a.a[c],a.b--))};td.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,sd(d[e]);delete this.a[c];this.b--}return b};_.wd=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=ud(a,c,d,e));return-1<b?a[b]:null};
xd=function(a){var b=_.p(void 0)?"undefined":void 0,c=_.p(b),d=c?b.toString():"",e=_.p(void 0);return Oa(a.a,function(a){for(var b=0;b<a.length;++b)if(!(c&&a[b].type!=d||e&&void 0!=a[b].capture))return!0;return!1})};ud=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.capture==!!c&&f.Sa==d)return e}return-1};
var yd,zd,Ad,Ed,Gd,Hd,Md,Ld,Id,Nd;yd="closure_lm_"+(1E6*Math.random()|0);zd={};Ad=0;_.Cd=function(a,b,c,d,e){if(d&&d.once)return _.Bd(a,b,c,d,e);if(_.ha(b)){for(var f=0;f<b.length;f++)_.Cd(a,b[f],c,d,e);return null}c=_.Dd(c);return _.pd(a)?a.listen(b,c,_.ka(d)?!!d.capture:!!d,e):Ed(a,b,c,!1,d,e)};
Ed=function(a,b,c,d,e,f){if(!b)throw Error("g");var h=_.ka(e)?!!e.capture:!!e,l=_.Fd(a);l||(a[yd]=l=new td(a));c=l.add(b,c,d,h,f);if(c.proxy)return c;d=Gd();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)ld||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Hd(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("h");Ad++;return c};
Gd=function(){var a=Id,b=jd?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};_.Bd=function(a,b,c,d,e){if(_.ha(b)){for(var f=0;f<b.length;f++)_.Bd(a,b[f],c,d,e);return null}c=_.Dd(c);return _.pd(a)?a.M(b,c,_.ka(d)?!!d.capture:!!d,e):Ed(a,b,c,!0,d,e)};
_.Jd=function(a,b,c,d,e){if(_.ha(b))for(var f=0;f<b.length;f++)_.Jd(a,b[f],c,d,e);else d=_.ka(d)?!!d.capture:!!d,c=_.Dd(c),_.pd(a)?a.g.remove(String(b),c,d,e):a&&(a=_.Fd(a))&&(b=_.wd(a,b,c,d,e))&&_.Kd(b)};
_.Kd=function(a){if(!_.ca(a)&&a&&!a.removed){var b=a.src;if(_.pd(b))vd(b.g,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Hd(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Ad--;(c=_.Fd(b))?(vd(c,a),0==c.b&&(c.src=null,b[yd]=null)):sd(a)}}};Hd=function(a){return a in zd?zd[a]:zd[a]="on"+a};
Md=function(a,b,c,d){var e=!0;if(a=_.Fd(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.removed&&(f=Ld(f,d),e=e&&!1!==f)}return e};Ld=function(a,b){var c=a.listener,d=a.Sa||a.src;a.Pa&&_.Kd(a);return c.call(d,b)};
Id=function(a,b){if(a.removed)return!0;if(!jd){var c=b||_.da("window.event");b=new nd(c,this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.b;e;e=e.parentNode)c.push(e);a=a.type;for(e=c.length-1;!b.c&&0<=e;e--){b.b=c[e];var f=Md(c[e],a,!0,b);d=d&&f}for(e=0;!b.c&&e<c.length;e++)b.b=c[e],f=Md(c[e],a,!1,b),d=d&&f}return d}return Ld(a,new nd(b,this))}; _.Fd=function(a){a=a[yd];return a instanceof td?a:null};Nd="__closure_events_fn_"+(1E9*Math.random()>>>0);_.Dd=function(a){if(_.ja(a))return a;a[Nd]||(a[Nd]=function(b){return a.handleEvent(b)});return a[Nd]};Lb(function(a){Id=a(Id)});
_.L=function(){_.F.call(this);this.g=new td(this);this.ha=this;this.F=null};_.u(_.L,_.F);_.L.prototype[od]=!0;_.L.prototype.I=function(a){this.F=a};_.L.prototype.removeEventListener=function(a,b,c,d){_.Jd(this,a,b,c,d)};
_.M=function(a,b){var c,d=a.F;if(d)for(c=[];d;d=d.F)c.push(d);a=a.ha;d=b.type||b;if(_.q(b))b=new _.K(b,a);else if(b instanceof _.K)b.target=b.target||a;else{var e=b;b=new _.K(d,a);_.Ra(b,e)}e=!0;if(c)for(var f=c.length-1;!b.c&&0<=f;f--){var h=b.b=c[f];e=h.pa(d,!0,b)&&e}b.c||(h=b.b=a,e=h.pa(d,!0,b)&&e,b.c||(e=h.pa(d,!1,b)&&e));if(c)for(f=0;!b.c&&f<c.length;f++)h=b.b=c[f],e=h.pa(d,!1,b)&&e;return e};_.L.prototype.v=function(){_.L.w.v.call(this);this.g&&this.g.removeAll(void 0);this.F=null};
_.L.prototype.listen=function(a,b,c,d){return this.g.add(String(a),b,!1,c,d)};_.L.prototype.M=function(a,b,c,d){return this.g.add(String(a),b,!0,c,d)};_.L.prototype.pa=function(a,b,c){a=this.g.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.capture==b){var h=f.listener,l=f.Sa||f.src;f.Pa&&vd(this.g,f);d=!1!==h.call(l,c)&&d}}return d&&0!=c.Bb};
var Od=function(){};Od.prototype.a=null;var Qd=function(a){var b;(b=a.a)||(b={},Pd(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var Rd,Sd=function(){};_.u(Sd,Od);var Td=function(a){return(a=Pd(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},Pd=function(a){if(!a.b&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.b=d}catch(e){}}throw Error("i");}return a.b};Rd=new Sd;
var Vd;_.Ud=function(a){if(a.T&&"function"==typeof a.T)return a.T();if(_.q(a))return a.split("");if(_.ia(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b};
Vd=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(_.ia(a)||_.q(a))(0,_.v)(a,b,void 0);else{if(a.X&&"function"==typeof a.X)var c=a.X();else if(a.T&&"function"==typeof a.T)c=void 0;else if(_.ia(a)||_.q(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else for(e in c=[],d=0,a)c[d++]=e;d=_.Ud(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}};
_.Wd=function(a,b){_.L.call(this);this.b=a||1;this.a=b||_.k;this.c=(0,_.t)(this.Ac,this);this.h=(0,_.m)()};_.u(_.Wd,_.L);_.g=_.Wd.prototype;_.g.sa=!1;_.g.Y=null;_.g.setInterval=function(a){this.b=a;this.Y&&this.sa?(this.stop(),this.start()):this.Y&&this.stop()};_.g.Ac=function(){if(this.sa){var a=(0,_.m)()-this.h;0<a&&a<.8*this.b?this.Y=this.a.setTimeout(this.c,this.b-a):(this.Y&&(this.a.clearTimeout(this.Y),this.Y=null),_.M(this,"tick"),this.sa&&(this.Y=this.a.setTimeout(this.c,this.b),this.h=(0,_.m)()))}};
_.g.start=function(){this.sa=!0;this.Y||(this.Y=this.a.setTimeout(this.c,this.b),this.h=(0,_.m)())};_.g.stop=function(){this.sa=!1;this.Y&&(this.a.clearTimeout(this.Y),this.Y=null)};_.g.v=function(){_.Wd.w.v.call(this);this.stop();delete this.a};_.Xd=function(a,b,c){if(_.ja(a))c&&(a=(0,_.t)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.t)(a.handleEvent,a);else throw Error("j");return 2147483647<Number(b)?-1:_.k.setTimeout(a,b||0)};_.Yd=function(a){_.k.clearTimeout(a)};
var Zd=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,$d=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?(0,window.decodeURIComponent)(e.replace(/\+/g," ")):"")}}};
var ae=function(a){_.L.call(this);this.headers=new _.J;this.o=a||null;this.b=!1;this.m=this.a=null;this.K="";this.c=this.D=this.h=this.A=!1;this.l=0;this.j=null;this.W="";this.P=this.N=!1},be,ce,de,le,ke,he,me;_.u(ae,_.L);be=/^https?$/i;ce=["POST","PUT"];de=[];_.ee=function(a,b,c,d,e,f,h){var l=new ae;de.push(l);b&&l.listen("complete",b);l.M("ready",l.ba);f&&(l.l=Math.max(0,f));h&&(l.N=h);l.send(a,c,d,e)};ae.prototype.ba=function(){this.$();_.za(de,this)};
ae.prototype.send=function(a,b,c,d){if(this.a)throw Error("k`"+this.K+"`"+a);b=b?b.toUpperCase():"GET";this.K=a;this.A=!1;this.b=!0;this.a=this.o?Td(this.o):Td(Rd);this.m=this.o?Qd(this.o):Qd(Rd);this.a.onreadystatechange=(0,_.t)(this.V,this);try{this.D=!0,this.a.open(b,String(a),!0),this.D=!1}catch(f){fe(this);return}a=c||"";var e=new _.J(this.headers);d&&Vd(d,function(a,b){e.set(b,a)});d=_.wa(e.X(),ge);c=_.k.FormData&&a instanceof _.k.FormData;!_.xa(ce,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
e.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.W&&(this.a.responseType=this.W);"withCredentials"in this.a&&this.a.withCredentials!==this.N&&(this.a.withCredentials=this.N);try{he(this),0<this.l&&((this.P=ie(this.a))?(this.a.timeout=this.l,this.a.ontimeout=(0,_.t)(this.R,this)):this.j=_.Xd(this.R,this.l,this)),this.h=!0,this.a.send(a),this.h=!1}catch(f){fe(this)}};var ie=function(a){return _.bb&&_.qb(9)&&_.ca(a.timeout)&&_.p(a.ontimeout)},ge=function(a){return"content-type"==a.toLowerCase()};
ae.prototype.R=function(){"undefined"!=typeof _.aa&&this.a&&(_.M(this,"timeout"),this.abort(8))};var fe=function(a){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);je(a);ke(a)},je=function(a){a.A||(a.A=!0,_.M(a,"complete"),_.M(a,"error"))};ae.prototype.abort=function(){this.a&&this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1,_.M(this,"complete"),_.M(this,"abort"),ke(this))};ae.prototype.v=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),ke(this,!0));ae.w.v.call(this)};
ae.prototype.V=function(){this.G||(this.D||this.h||this.c?le(this):this.L())};ae.prototype.L=function(){le(this)};le=function(a){if(a.b&&"undefined"!=typeof _.aa&&(!a.m[1]||4!=(a.a?a.a.readyState:0)||2!=me(a)))if(a.h&&4==(a.a?a.a.readyState:0))_.Xd(a.V,0,a);else if(_.M(a,"readystatechange"),4==(a.a?a.a.readyState:0)){a.b=!1;try{_.ne(a)?(_.M(a,"complete"),_.M(a,"success")):je(a)}finally{ke(a)}}};
ke=function(a,b){if(a.a){he(a);var c=a.a,d=a.m[0]?_.ea:null;a.a=null;a.m=null;b||_.M(a,"ready");try{c.onreadystatechange=d}catch(e){}}};he=function(a){a.a&&a.P&&(a.a.ontimeout=null);a.j&&(_.Yd(a.j),a.j=null)};
_.ne=function(a){var b=me(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.K).match(Zd)[1]||null,!a&&_.k.self&&_.k.self.location&&(a=_.k.self.location.protocol,a=a.substr(0,a.length-1)),b=!be.test(a?a.toLowerCase():"");c=b}return c};me=function(a){try{return 2<(a.a?a.a.readyState:0)?a.a.status:-1}catch(b){return-1}};Lb(function(a){ae.prototype.L=a(ae.prototype.L)});
var pe;_.O=function(a){_.F.call(this);this.P=a;this.o={}};_.u(_.O,_.F);var oe=[];_.O.prototype.listen=function(a,b,c,d){_.ha(b)||(b&&(oe[0]=b.toString()),b=oe);for(var e=0;e<b.length;e++){var f=_.Cd(a,b[e],c||this.handleEvent,d||!1,this.P||this);if(!f)break;this.o[f.key]=f}return this};_.qe=function(a,b,c,d){pe(a,b,c,d,void 0)};pe=function(a,b,c,d,e,f){if(_.ha(c))for(var h=0;h<c.length;h++)pe(a,b,c[h],d,e,f);else(b=_.Bd(b,c,d||a.handleEvent,e,f||a.P||a))&&(a.o[b.key]=b)}; _.O.prototype.removeAll=function(){_.Na(this.o,function(a,b){this.o.hasOwnProperty(b)&&_.Kd(a)},this);this.o={}};_.O.prototype.v=function(){_.O.w.v.call(this);this.removeAll()};_.O.prototype.handleEvent=function(){throw Error("l");};
_.re=function(a){_.B(this,a,0,null,null)};_.u(_.re,_.y);var te=function(a,b){var c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("m");return d.replace(/%([0\- \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(a,b,d,l,n,r,w,N){if("%"==r)return"%";var e=c.shift();if("undefined"==typeof e)throw Error("n");arguments[0]=e;return se[r].apply(null,arguments)})},se={s:function(a,b,c){return(0,window.isNaN)(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",0)?a+Ga(" ",Number(c)-a.length):Ga(" ",Number(c)-a.length)+a},f:function(a,
b,c,d,e){d=a.toString();(0,window.isNaN)(e)||""==e||(d=(0,window.parseFloat)(a).toFixed(e));var f=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(d=f+d);if((0,window.isNaN)(c)||d.length>=Number(c))return d;d=(0,window.isNaN)(e)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(e);a=Number(c)-d.length-f.length;return d=0<=b.indexOf("-",0)?f+d+Ga(" ",a):f+Ga(0<=b.indexOf("0",0)?"0":" ",a)+d},d:function(a,b,c,d,e,f,h,l){return se.f((0,window.parseInt)(a,10),b,c, d,0,f,h,l)}};se.i=se.d;se.u=se.d;
_.P=function(a,b){for(var c=[],d=0;d<arguments.length;d++)if(arguments[d]instanceof Error)c.push(arguments[d].stack);else if("object"==typeof arguments[d])try{c.push(JSON.stringify(arguments[d]))}catch(e){c.push("_error_("+e+")")}else c.push(arguments[d]);window.console&&(d=new Date,d=te("%02d-%02d ",d.getMonth()+1,d.getDate())+d.toLocaleTimeString(void 0,{hour12:!1})+te(".%03d",d.getMilliseconds()),window.console.log(d+" info: "+te.apply({},c)))};
_.ve=function(a){_.B(this,a,"h_exts",ue,null)};_.u(_.ve,_.y);var ue=[2];_.ve.messageId="h_exts";var we,xe,ye,Be,De,Me,Ee,Ge,Fe,Je,He,Ce,Pe;_.Q=function(a,b){this.b=this.j=this.h="";this.c=null;this.l=this.a="";this.C=!1;var c;a instanceof _.Q?(this.C=_.p(b)?b:a.C,we(this,a.h),this.j=a.j,this.b=a.b,xe(this,a.c),this.a=a.a,ye(this,ze(a.g)),_.Ae(this,a.l)):a&&(c=String(a).match(Zd))?(this.C=!!b,we(this,c[1]||"",!0),this.j=Be(c[2]||""),this.b=Be(c[3]||"",!0),xe(this,c[4]),this.a=Be(c[5]||"",!0),ye(this,c[6]||"",!0),_.Ae(this,c[7]||"",!0)):(this.C=!!b,this.g=new Ce(null,this.C))};
_.Q.prototype.toString=function(){var a=[],b=this.h;b&&a.push(De(b,Ee,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.j)&&a.push(De(b,Ee,!0),"@"),a.push((0,window.encodeURIComponent)(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.c,null!=c&&a.push(":",String(c));if(c=this.a)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(De(c,"/"==c.charAt(0)?Fe:Ge,!0));(c=this.g.toString())&&a.push("?",c);(c=this.l)&&a.push("#",De(c,He));return a.join("")};
we=function(a,b,c){a.h=c?Be(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))};xe=function(a,b){if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("q`"+b);a.c=b}else a.c=null};ye=function(a,b,c){b instanceof Ce?(a.g=b,Ie(a.g,a.C)):(c||(b=De(b,Je)),a.g=new Ce(b,a.C))};_.R=function(a,b,c){a.g.set(b,c)};_.Ae=function(a,b,c){a.l=c?Be(b):b};_.Ke=function(a){return a instanceof _.Q?new _.Q(a):new _.Q(a,void 0)};
_.Le=function(a,b){a instanceof _.Q||(a=_.Ke(a));b instanceof _.Q||(b=_.Ke(b));var c=a;a=new _.Q(c);var d=!!b.h;d?we(a,b.h):d=!!b.j;d?a.j=b.j:d=!!b.b;d?a.b=b.b:d=null!=b.c;var e=b.a;if(d)xe(a,b.c);else if(d=!!b.a)if("/"!=e.charAt(0)&&(c.b&&!c.a?e="/"+e:(c=a.a.lastIndexOf("/"),-1!=c&&(e=a.a.substr(0,c+1)+e))),".."==e||"."==e)e="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){c=_.Ca(e,"/");e=e.split("/");for(var f=[],h=0;h<e.length;){var l=e[h++];"."==l?c&&h==e.length&&f.push(""):".."==l?((1<f.length||
1==f.length&&""!=f[0])&&f.pop(),c&&h==e.length&&f.push("")):(f.push(l),c=!0)}e=f.join("/")}d?a.a=e:d=""!==b.g.toString();d?ye(a,ze(b.g)):d=!!b.l;d&&_.Ae(a,b.l);return a};Be=function(a,b){return a?b?(0,window.decodeURI)(a.replace(/%25/g,"%2525")):(0,window.decodeURIComponent)(a):""};De=function(a,b,c){return _.q(a)?(a=(0,window.encodeURI)(a).replace(b,Me),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};Me=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};
Ee=/[#\/\?@]/g;Ge=/[#\?:]/g;Fe=/[#\?]/g;Je=/[#\?@]/g;He=/#/g;Ce=function(a,b){this.b=this.a=null;this.g=a||null;this.c=!!b};Pe=function(a){a.a||(a.a=new _.J,a.b=0,a.g&&$d(a.g,function(b,c){a.add((0,window.decodeURIComponent)(b.replace(/\+/g," ")),c)}))};Ce.prototype.add=function(a,b){Pe(this);this.g=null;a=Qe(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};
Ce.prototype.remove=function(a){Pe(this);a=Qe(this,a);return _.hd(this.a,a)?(this.g=null,this.b-=this.a.get(a).length,this.a.remove(a)):!1};Ce.prototype.clear=function(){this.a=this.g=null;this.b=0};var Re=function(a,b){Pe(a);b=Qe(a,b);return _.hd(a.a,b)};_.g=Ce.prototype;_.g.forEach=function(a,b){Pe(this);this.a.forEach(function(c,d){(0,_.v)(c,function(c){a.call(b,c,d,this)},this)},this)};
_.g.X=function(){Pe(this);for(var a=this.a.T(),b=this.a.X(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};_.g.T=function(a){Pe(this);var b=[];if(_.q(a))Re(this,a)&&(b=_.Aa(b,this.a.get(Qe(this,a))));else{a=this.a.T();for(var c=0;c<a.length;c++)b=_.Aa(b,a[c])}return b};_.g.set=function(a,b){Pe(this);this.g=null;a=Qe(this,a);Re(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};
_.g.get=function(a,b){a=a?this.T(a):[];return 0<a.length?String(a[0]):b};_.Se=function(a,b,c){a.remove(b);0<c.length&&(a.g=null,a.a.set(Qe(a,b),_.Ba(c)),a.b+=c.length)};Ce.prototype.toString=function(){if(this.g)return this.g;if(!this.a)return"";for(var a=[],b=this.a.X(),c=0;c<b.length;c++){var d=b[c],e=(0,window.encodeURIComponent)(String(d));d=this.T(d);for(var f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+(0,window.encodeURIComponent)(String(d[f])));a.push(h)}}return this.g=a.join("&")};
var ze=function(a){var b=new Ce;b.g=a.g;a.a&&(b.a=new _.J(a.a),b.b=a.b);return b},Qe=function(a,b){b=String(b);a.c&&(b=b.toLowerCase());return b},Ie=function(a,b){b&&!a.c&&(Pe(a),a.g=null,a.a.forEach(function(a,b){var c=b.toLowerCase();b!=c&&(this.remove(b),_.Se(this,c,a))},a));a.c=b};
var Te;Te=function(a){return(a=a.exec(_.Ka))?a[1]:""};_.Ue=function(){if(tb)return Te(/Firefox\/([0-9.]+)/);if(_.bb||cb||ab)return ob;if(xb)return Ua()?Te(/CriOS\/([0-9.]+)/):Te(/Chrome\/([0-9.]+)/);if(yb&&!Ua())return Te(/Version\/([0-9.]+)/);if(ub||vb){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.Ka);if(a)return a[1]+"."+a[2]}else if(wb)return(a=Te(/Android\s+([0-9.]+)/))?a:Te(/Version\/([0-9.]+)/);return""}();
var Ve=function(a,b){_.K.call(this,a,b);this.U=b};_.u(Ve,_.K);var We=function(a){_.B(this,a,"capi_md1571",null,null)};_.u(We,_.y);var Xe={sb:0,Gc:1,Ec:2,rb:3,eb:4};We.messageId="capi_md1571";var Ye=function(a){_.B(this,a,0,null,null)};_.u(Ye,_.y);var $e=function(){for(var a=10,b=Ze,c=b.length,d="";0<a--;)d+=b.charAt(Math.floor(Math.random()*c));return d},Ze="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";_.af=function(a,b){_.F.call(this);this.j=b||$e();this.c=this.a="";this.b=this.g=null;this.l=a;this.h=new _.O(this);_.I(this,this.h);this.h.listen(window,"message",this.m)};_.u(_.af,_.F);_.af.prototype.da=function(a,b,c){this.c=a;this.g=b;this.b=c};
_.af.prototype.m=function(a){a=a.a;var b=a.origin;this.g&&this.g!=a.source||"*"!=this.c&&this.c!=b?b=!1:this.b?(b=(new _.Q(b)).b,b=_.Da(b,this.b)?b.length==this.b.length||"."==this.b[0]||"."==b[b.length-1-this.b.length]:!1):b=!0;if(b&&(b=a.data)&&_.q(b)&&"["==b[0]){try{var c=JSON.parse(b);if(!_.ha(c))return}catch(d){return}if(0!=c.length&&"capi_md1571"==c[0]&&(c=new We(c),_.z(c,1)==this.j)){b=_.z(c,3);if(!this.a)this.a=b;else if(this.a!=b)return;"*"!=this.c&&this.g||this.da(a.origin,a.source);1==
_.z(c,2)?this.send(2):this.l(c,a)}}};_.af.prototype.send=function(a,b,c){if(this.a&&this.g){b=b||new We;_.A(b,3,this.j);_.A(b,1,this.a);_.A(b,2,a);var d=JSON.stringify(_.D(b)),e=this.g,f=this.c;_.bb?_.Xd(function(){e.postMessage(d,f)}):c?e.postMessage(d,f,c):e.postMessage(d,f)}};
var bf=function(a,b,c,d){this.g=_.ic();this.a=new _.af((0,_.t)(this.h,this),c);this.a.da("*",a,d);this.a.a=b;this.b=new _.Wd(50);this.b.start();_.Cd(this.b,"tick",this.c,!1,this);this.c();a=this.g.a;b=this.C;b=gc(b,b,this);b.g=!0;pc(a,b)};bf.prototype.C=function(){_.H(this.a);_.Jd(this.b,"tick",this.c,!1,this);_.H(this.b)};bf.prototype.c=function(){this.a.send(1)};bf.prototype.h=function(a,b){2==_.z(a,2)&&this.g.b(b.origin)};
var cf=function(a,b,c){_.F.call(this);this.b=a;a=_.z(b,3);b=_.z(b,1);this.a=new _.af((0,_.t)(this.g,this),b);this.a.a=a;c&&this.a.da(c.origin,c.source);_.I(this,this.a)};_.u(cf,_.F);cf.prototype.send=function(a){var b=new We;_.E(b,4,a);this.a.send(Xe.sb,b)};cf.prototype.connect=function(a,b){this.a.da(a,b);this.a.send(Xe.rb)};cf.prototype.g=function(a){_.z(a,2)==Xe.sb&&(a=_.C(a,Ye,4),this.b(a))};cf.prototype.c=_.ea;
var ef=function(a,b,c){_.F.call(this);this.h=a;this.b=this.a=this.g=null;c?(this.b=c.ports[0],df(this)):(this.a=new _.af(_.ea,_.z(b,1)),a=_.z(b,3),this.a.a=a)};_.u(ef,_.F);ef.prototype.v=function(){ef.w.v.call(this);this.b&&this.b.close();_.H(this.a)};ef.prototype.c=function(){this.g=new _.O(this);_.I(this,this.g);df(this)};ef.prototype.send=function(a){this.b.postMessage(_.D(a))};
ef.prototype.connect=function(a,b){var c=new window.MessageChannel;this.b=c.port1;df(this);var d=this.a;this.a=null;c=c.port2;d.da(a,b);d.send(Xe.eb,void 0,[c]);_.H(d)};var df=function(a){a.b&&a.g&&(a.g.listen(a.b,"message",a.j),a.b.start())};ef.prototype.j=function(a){a=a.a;try{var b=new Ye(a.data)}catch(c){return}this.h(b)};
var ff=function(a,b,c){var d=!1;_.p(_.z(b,2))?_.z(b,2)==Xe.eb&&(d=!0):d=xb;return d?new ef(a,b,c):new cf(a,b,c)};var lf,nf;_.gf=function(){_.L.call(this);this.j=null;this.l=!1;this.h=[];this.c=[];_.G(this,this.o,this);this.b=null};_.u(_.gf,_.L);_.gf.prototype.o=function(){for(;this.c.length;)this.c.shift()()};_.jf=function(a){a.o();a.h=[];a.b=new _.uc;a.c.push((0,_.t)(a.b.cancel,a.b));a.l=!1;_.Bc(a.b.b(),function(a){(xd(this.g)||this.F)&&_.hf(this);this.c.push(_.na(_.H,a))},a)};_.gf.prototype.sendMessage=function(a){kf(this,_.D(a))};var kf=function(a,b){if(a.b){var c=new Ye;_.A(c,1,b);_.Bc(a.b.b(),function(a){a.send(c)})}};
_.gf.prototype.H=function(){return this};_.gf.prototype.da=function(a,b,c){this.a.da(a,b,c)};_.mf=function(a,b,c,d){_.jf(a);lf(a,b,c,d).then(function(a){var d=new We;_.A(d,1,a.Bc);_.A(d,3,c);d=ff((0,_.t)(this.m,this),d);d.connect(a.origin,b);this.b.g(d)},void 0,a)};lf=function(a,b,c,d){var e=$e();b=(new bf(b,c,e,d)).g.a;a.c.push((0,_.t)(b.cancel,b));return b.then(function(a){return{Bc:e,origin:a}})};
_.gf.prototype.D=function(a,b){if(_.z(a,2)==Xe.rb||_.z(a,2)==Xe.eb)_.H(this.a),this.a=null,this.b.g(ff((0,_.t)(this.m,this),a,b))};_.gf.prototype.m=function(a){this.h.push(a);this.A()};_.gf.prototype.A=function(){for(;nf(this););};nf=function(a){if(a.G||!a.l||0==a.h.length)return!1;var b=_.z(a.h.shift(),1);a.j&&kf(a.j,b);_.M(a,new Ve(b[0],b));return!0};_.hf=function(a){a.l||(a.l=!0,a.b&&_.Bc(a.b.b(),function(a){a.c();_.Xd(this.A,0,this)},a))}; _.gf.prototype.listen=function(a,b,c,d){_.hf(this);return _.gf.w.listen.call(this,a,b,c,d)};_.gf.prototype.M=function(a,b,c,d){_.hf(this);return _.gf.w.M.call(this,a,b,c,d)};_.gf.prototype.I=function(a){_.hf(this);return _.gf.w.I.call(this,a)};
var of=function(a){this.b=a;this.c="empty";this.a=null;this.g={}};of.prototype.ca=function(a){this.c=a;return this};of.prototype.ta=function(a){this.a=a;return this};of.prototype.qb=function(a){this.g=_.Pa(a);return this};var pf=function(){};var qf=function(){};_.u(qf,pf);qf.prototype.clear=function(){var a=ed(this.ia(!0)),b=this;(0,_.v)(a,function(a){b.remove(a)})};var rf=function(a){this.a=a};_.u(rf,qf);_.g=rf.prototype;_.g.isAvailable=function(){if(!this.a)return!1;try{return this.a.setItem("__sak","1"),this.a.removeItem("__sak"),!0}catch(a){return!1}};_.g.set=function(a,b){try{this.a.setItem(a,b)}catch(c){if(0==this.a.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};_.g.get=function(a){a=this.a.getItem(a);if(!_.q(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};_.g.remove=function(a){this.a.removeItem(a)};
_.g.ia=function(a){var b=0,c=this.a,d=new bd;d.next=function(){if(b>=c.length)throw ad;var d=c.key(b++);if(a)return d;d=c.getItem(d);if(!_.q(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};_.g.clear=function(){this.a.clear()};_.g.key=function(a){return this.a.key(a)};
var sf=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.a=a};_.u(sf,rf);var uf=function(a,b){this.g=a;this.a=[];this.b=null;b&&(this.b=new sf);if(null!=this.b&&this.b.isAvailable()&&(a=this.b.get("__webmonitoring_RateThrottler_history_hourlyRate"),null!=a))try{this.a=JSON.parse(a)||[]}catch(c){}a=!1;_.ha(this.a)||(this.a=[],a=!0);for(;this.a.length>this.g;)this.a.shift(),a=!0;a&&tf(this)},tf=function(a){if(null!=a.b&&a.b.isAvailable())try{a.b.set("__webmonitoring_RateThrottler_history_hourlyRate",_.Xc(a.a))}catch(b){}};
var vf=function(a){_.F.call(this);this.a=a;this.h=!1};_.u(vf,_.F);vf.prototype.setEnabled=function(a){this.h=a};var S=function(a){vf.call(this,a);this.o=100;this.m={};this.O=null;this.g="";this.F=!0;this.j=10;this.b=null;this.c=!1};_.u(S,vf);S.prototype.Fb=function(a){this.F=a;return this};S.prototype.setUseLocalStorage=S.prototype.Fb;S.prototype.zc=function(a){this.j=Math.min(a,100);return this};S.prototype.setMaxErrorsPerHour=S.prototype.zc;S.prototype.Db=function(a){this.o=a;return this};S.prototype.setGlobalSampling=S.prototype.Db;S.prototype.ub=function(a,b){this.m[a]=b;return this};
S.prototype.addPerErrorMessageSampling=S.prototype.ub;S.prototype.Cb=function(a){this.O=a;return this};S.prototype.setCallback=S.prototype.Cb;S.prototype.yc=function(a){this.g=a;return this};S.prototype.setClientId=S.prototype.yc;S.prototype.enable=function(){if(this.h)return!1;this.l=window.onerror;window.onerror=this.A.bind(this);this.setEnabled(!0);return!0};S.prototype.enable=S.prototype.enable;
S.prototype.zb=function(a,b,c,d,e){var f=_.Ke(window.location.href);a=null!=e&&null!=e.message?e.message:a;var h;if(h=!_.ja(this.O)||this.O(f.a,a,b,c,d,e))if(h=this.c){h=Object.keys(this.m);for(var l=100,n=0;n<h.length;++n){var r=h[n];(new RegExp(r)).test(a)&&(l=this.m[r])}if(h=(100*Math.random()).toFixed(6)>=this.o*l/100?!1:!0){0<=this.j&&null===this.b&&(this.b=new uf(this.j,this.F));if(null===this.b)h=!1;else{a:{h=this.b;l=(0,_.m)();if(h.a.length==h.g)if(h.a[0]<l-36E5)h.a.shift();else{h=!1;break a}h.a.push(l);
tf(h);h=!0}h=!h}h=!h&&this.c}}h&&(h=_.Pa(this.a.g),h.url=f.a,h.type="JavascriptError",h.error_message=a,l="Other",ab?l="Opera":_.bb?l="Internet Explorer":tb?l="Firefox":xb?l="Chrome":yb&&(l="Safari"),h.browser=l,h.browser_version=_.Ue,h.os=_.Xa()?"Chrome OS":_.x("Linux")?"Linux":_.Wa()?"Windows":_.x("Android")?"Android":Ta()?"iPhone":_.x("iPad")?"iPad":_.x("iPod")?"iPod":_.Va()?"Mac":"Unknown",l=_.Ka,n="",_.Wa()?(n=/Windows (?:NT|Phone) ([0-9.]+)/,n=(l=n.exec(l))?l[1]:"0.0"):Ua()?(n=/(?:iPhone|iPod|iPad|CPU)\s+OS\s+(\S+)/,
n=(l=n.exec(l))&&l[1].replace(/_/g,".")):_.Va()?(n=/Mac OS X ([0-9_.]+)/,n=(l=n.exec(l))?l[1].replace(/_/g,"."):"10"):_.x("Android")?(n=/Android\s+([^\);]+)(\)|;)/,n=(l=n.exec(l))&&l[1]):_.Xa()&&(n=/(?:CrOS\s+(?:i686|x86_64)\s+([0-9.]+))/,n=(l=n.exec(l))&&l[1]),h.os_version=n||"",null!=this.a.a&&(h.channel=this.a.a),_.Ea(this.g)||(h.guid=this.g),null!=b&&(h.src=b),null!=c&&(h.line=c),null!=d&&(h.column=d),h.prod=this.a.b,h.ver=this.a.c,c=null!=e?_.Ha(e.stack):"",b=wf(h),_.Ea(a)||(d=c.split("\n"),
-1<d[0].indexOf(a)&&(d.splice(0,1),c=d.join("\n"))),xf(this,"https://clients2.google.com/cr/staging_report",b,c),f={product:this.a.b,url:f.a,js_errors_count:"1"},a=_.Ha(this.a.a),_.Ea(a)||(f.version=a),xf(this,"https://clients2.google.com/cr/staging_perf",wf(f)))};S.prototype.reportError=S.prototype.zb;S.prototype.A=function(a,b,c,d,e){this.zb(a,b,c,d,e);null!=this.l&&_.ja(this.l)&&this.l(a,b,c,d,e)};
var wf=function(a){var b="",c;for(c in a)b+=_.Ea(b)?"?":"&",b+=c+"="+(0,window.encodeURIComponent)(a[c]);return b},xf=function(a,b,c,d){d=d||"";var e=_.Ea(d)?{}:{"Content-Type":"text/plain"};_.ee(b+c,a.I.bind(a,b),"POST",d,e,6E4,!0)};S.prototype.I=function(a,b){_.ne(b.target)};
var yf=function(a){vf.call(this,a);this.O=null;this.b=0};_.u(yf,vf);yf.prototype.Cb=function(a){this.O=a;return this};var zf=[{age:6E4,name:"1m"},{age:15E5,name:"25m"},{age:36E5,name:"1h"},{age:36E6,name:"10h"}];yf.prototype.enable=function(){if(this.h)return!1;if(window.performance&&window.performance.memory){var a=new _.Wd(6E4);_.I(this,a);var b=new _.O(this);_.I(this,b);b.listen(a,"tick",this.g);a.start();this.setEnabled(!0);return!0}return!1};
yf.prototype.g=function(){this.b+=6E4;for(var a="",b=0;b<zf.length;++b)if(this.b==zf[b].age){a=zf[b].name;break}if(""!=a){b=Af.test(_.Ka)?"":"32_bit_";var c=window.performance.memory;if(c.totalJSHeapSize&&c.usedJSHeapSize){a=[{name:"total_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Total JS heap (MB)",value:Math.round(c.totalJSHeapSize/1048576)},{name:"used_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Used JS heap (MB)",value:Math.round(c.usedJSHeapSize/1048576)}];b=_.Ke(window.location.href).a;
c="?product="+(0,window.encodeURIComponent)(this.a.b)+"&url="+(0,window.encodeURIComponent)(b);var d=_.Ha(this.a.a);_.Ea(d)||(c+="&version="+(0,window.encodeURIComponent)(d));for(d=0;d<a.length;++d)c+="&"+(0,window.encodeURIComponent)(a[d].name)+"="+a[d].value,_.ja(this.O)&&this.O(b,a[d].displayName,a[d].value);_.ee("https://clients2.google.com/cr/staging_perf"+c,Bf,"POST","",null,6E4,!0)}}};var Bf=function(a){_.ne(a.target)},Af=/(x86_64|Win64)/;
var Cf=function(a){_.F.call(this);this.b=new of(a);this.a={}};_.u(Cf,_.F);_.oa("webmonitoring.Monitoring",Cf);Cf.prototype.ca=function(a){this.b.ca(a);return this};Cf.prototype.setVersion=Cf.prototype.ca;Cf.prototype.ta=function(a){this.b.ta(a);return this};Cf.prototype.setChannel=Cf.prototype.ta;Cf.prototype.qb=function(a){this.b.qb(a);return this};Cf.prototype.setContext=Cf.prototype.qb;Cf.prototype.Qa=function(){null!=this.a[2]||(this.a[2]=new S(this.b));return this.a[2]}; Cf.prototype.createJsErrorsReporter=Cf.prototype.Qa;
var Df=function(a){Cf.call(this,a)};_.u(Df,Cf);Df.prototype.ca=function(a){return Df.w.ca.call(this,a)};Df.prototype.ta=function(a){return Df.w.ta.call(this,a)};Df.prototype.Qa=function(){var a=Df.w.Qa.call(this);a.c=!0;return a};_.Ef=function(){var a=new Df("Google_Hangouts_Chrome");a.ta(window.chrome.runtime.id);a.ca(window.chrome.runtime.getManifest().version);null!=a.a[1]||(a.a[1]=new yf(a.b));a.a[1].enable();a.Qa().Fb(!1).Db(100).ub("Script error.",0).enable()};
}catch(e){_._DumpException(e)}
/* _Module_:host */
try{
var dp=function(a,b){_.jc(a,null,b,void 0)},ep=function(a){_.B(this,a,"uv_r_hrd",null,null)};_.u(ep,_.y);ep.messageId="uv_r_hrd";
var fp=function(a,b){return a.g.get(b)},gp=function(a,b){a.j=b;_.G(a,function(){this.j=null},a);_.hf(a)},hp=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.ia(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var h=0;h<f;h++)a[e+h]=d[h]}else a.push(d)}},ip=function(a){var b=new _.gf;_.jf(b);b.a=new _.af((0,_.t)(b.D,b),a);b.a.da("*",void 0,void 0);b.c.push(_.na(_.H,b.a));return b};
var jp=function(a){this.a=a;_.bb||(delete this.a.lpu,delete this.a.ppu)},kp=["cn","tp"],lp=function(a,b){if(_.ja(window.document.postMessage)||_.ja(window.postMessage)||_.bb&&window.postMessage)var c=1;else if(_.db)c=2;else{var d;if(d=_.bb){d=!1;try{c=window.opener,window.opener={},d=_.Za(window,"opener"),window.opener=c}catch(e){}}c=d?6:4}d={};d.cn=Math.floor(2147483648*Math.random()).toString(36);d.tp=c;d.ifrid=b;d.pu=a;return new jp(d)};_.oa("GTalk_IFrameChannelConfig.build",lp);
var mp=function(){},pp=function(a){var b=a.oa,c=function(a){c.w.constructor.call(this,a);var b=this.Z.length;this.a=[];for(var d=0;d<b;++d)this.Z[d].Vc||(this.a[d]=new this.Z[d](a))};_.u(c,b);for(var d=[];a;){if(b=a.oa){b.Z&&hp(d,b.Z);var e=b.prototype,f;for(f in e)if(e.hasOwnProperty(f)&&_.ja(e[f])&&e[f]!==b){var h=!!e[f].Ub,l=np(f,e,d,h);(h=op(f,e,l,h))&&(c.prototype[f]=h)}}a=a.w&&a.w.constructor}c.prototype.Z=d;return c},np=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||
(e.push(f),!d));++f);return e},op=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.Z[c[0]].prototype[a].apply(this,arguments)}:b[a].Wb?e=function(b){a:{var d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var f=this.a[c[e]];if(f=f?f[a].apply(f,d):this.Z[c[e]].prototype[a].apply(this,d)){d=f;break a}}d=!1}return d}:b[a].Vb?e=function(b){a:{var d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var f=
this.a[c[e]];f=f?f[a].apply(f,d):this.Z[c[e]].prototype[a].apply(this,d);if(null!=f){d=f;break a}}d=void 0}return d}:b[a].lc?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var f=this.a[c[e]];f?f[a].apply(f,d):this.Z[c[e]].prototype[a].apply(this,d)}}:e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],f=0;f<c.length;++f){var r=this.a[c[f]];e.push(r?r[a].apply(r,d):this.Z[c[f]].prototype[a].apply(this,d))}return e}:d||b[a].Wb||b[a].Vb||b[a].lc? e=null:e=qp;return e},qp=function(){return[]};mp.prototype.h=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};var rp=function(a){(a?a:function(){}).Ub=!0};
var sp=function(){};_.u(sp,mp);sp.prototype.b=function(a){return a};rp(sp.prototype.b);sp.prototype.g=function(){return!0};rp(sp.prototype.g);var tp=function(a){_.B(this,a,0,null,null)};_.u(tp,_.y);var up=function(a,b){var c=new tp;_.A(c,1,b);_.A(c,2,a);return c},vp=up("?",0),wp=up("q",1),xp=up("<",2),yp=up(">",3),zp=up("~",4),Ap=up("s",5),Bp={Fc:vp,Oc:wp,Ic:xp,Jc:yp,Hc:zp,Qc:Ap};var Cp=function(a){_.B(this,a,"h_cc",null,null)};_.u(Cp,_.y);var Dp=function(a){_.B(this,a,0,null,null)};_.u(Dp,_.y);var Ep=function(a){_.B(this,a,0,null,null)};_.u(Ep,_.y);var Fp=function(a){_.B(this,a,0,null,null)};_.u(Fp,_.y);var Gp=function(a){_.B(this,a,0,null,null)};_.u(Gp,_.y);Cp.messageId="h_cc";var Hp=function(a,b){_.A(a,3,b)},Ip=function(a,b){_.A(a,4,b)},Jp=function(a,b){_.A(a,11,b)};
var Kp=function(a){_.B(this,a,"ci:ec",null,null)};_.u(Kp,_.y);Kp.messageId="ci:ec";var Lp=function(a){return this.lb.h(a)};var Mp=function(){this.a=window.document||{cookie:""}};_.g=Mp.prototype;_.g.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("D`"+a);if(/[;\r\n]/.test(b))throw Error("E`"+b);_.p(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,_.m)()+1E3*c)).toUTCString();this.a.cookie=a+"="+b+e+d+c+f};
_.g.get=function(a,b){for(var c=a+"=",d=(this.a.cookie||"").split(";"),e=0,f;e<d.length;e++){f=(0,_.Fa)(d[e]);if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};_.g.remove=function(a,b,c){var d=_.p(this.get(a));this.set(a,"",0,b,c);return d};_.g.X=function(){return Np(this).keys};_.g.T=function(){return Np(this).values};_.g.clear=function(){for(var a=Np(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])}; var Np=function(a){a=(a.a.cookie||"").split(";");for(var b=[],c=[],d,e,f=0;f<a.length;f++)e=(0,_.Fa)(a[f]),d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
var Op=function(a,b){if(!this.lb){for(var c=this.constructor;c&&!c.oa;)c=c.w&&c.w.constructor;c.oa.xb||(c.oa.xb=pp(c));this.lb=new c.oa.xb(this);this.h||(this.h=Lp)}var d=this.lb.b(a.clientBaseUrl||"https://talkgadget.google.com/talkgadget/");if(_.Ca(d,"https://talkgadget.google.com/talkgadget/")){c=(new Mp).get("WCSDBG","");c=c.split(";")[0];c=c.split("|")[0];var e=["plus.google.com"],f=/^[-_a-zA-Z0-9\.]+\.talkgadget\.google\.com$/;0<c.length&&!_.xa(e,c)&&f.test(c)&&(d=_.Ke(d),d=_.Ke("https://"+
c+d.a).toString())}this.g=d;this.c=b||new Kp;a.notificationsOnly&&_.A(this.c,1,!0);this.b="0";null!=a.authUser?this.b=a.authUser:(b=fp(new _.Q(window.location.href),"authuser"),null!=b&&(this.b=b));this.o=a.clientUrl||"notifierclient";b=fp(_.Ke(this.o),"authuser");null!=b&&(this.b=b);this.Ta=a.propertyName||"Google Talk";this.I=a.cssUrl;this.locale=a.locale;this.j=a.debug;this.Oa=a.userJid;this.La=a.uiVersion;this.ec=null!=a.rosterExpanded?a.rosterExpanded:!0;this.W=a.hostLogMinValue;this.za=a.hideChat;
this.Yb=a.refresh;this.P=a.hideProfileCard;this.V=a.hideStatusMsgs;this.R=a.hideRosterOptions;this.N=a.hideRecentConversations;this.L=a.hideOTR;this.jb=a.hostServerMessageCallback||!1;this.ba=a.isCentralRoster;this.Xb=a.isFullFrame||!1;this.dc=a.rosterClass||"talk_roster";this.gc=a.rosterId||"talk_roster";this.a="gtn-roster-iframe-id";a.rosterFrameId&&a.rosterFrameId.match(/[\w-]/)&&(this.a=a.rosterFrameId);a.rosterIframeIdB&&a.rosterIframeIdB.match(/[\w-]/);this.ya=a.parentToken;_.p(a.isRtl)||_.Gc.test(this.locale);
this.l=a.position||"l";if(!a.keyboardShortcuts){b=[];for(var h in Bp)b.push(_.D(Bp[h]))}this.D=a.entityId;this.Ma=a.useQuasarPanels||!1;this.Ja=a.silent||!1;this.kb=a.ignoreCentralRoster||!1;this.$b=a.lazy||!1;this.gb=a.handleProfileLinks||!1;this.ha=a.hostSettings;this.m=a.screen;this.A=a.docsConfig;this.Zb=a.jsmode;this.xa=a.moleWidth;this.wa=a.moleHeight;this.va=a.minimizedMoleHeight||36;this.hc=a.derp;this.Ka=window.location.protocol+"//"+window.location.host;this.C="";this.K=a.optOutAllowed;
this.M=a.legacyTalkSignedIn;this.Na=a.useSpareMole;this.F=a.conversationId};sp.w||_.u(sp,mp);Op.oa=sp;
var Qp=function(a){var b={},c=_.Db(a,1,"hangouts.google.com"),d="";0>c.indexOf("://")&&(d="https://",0<=c.indexOf(":")&&23!=_.z(a,2)&&27!=_.z(a,2)&&(d="http://"));b.clientBaseUrl=d+c+"/webchat/u/"+_.Db(a,8,"0")+"/";b.clientUrl="load";b.authUser=_.Db(a,8,"0");b.propertyName=Pp(_.z(a,2));b.locale=_.z(a,4);b.hideProfileCard=!0;b.parentToken=_.z(a,3);b.isRtl=_.Db(a,6,!1);b.lazy=_.Db(a,7,!1);b.entityId=_.z(a,9);b.hostSettings=_.z(a,5);b.jsmode=_.z(a,11);b.isFullFrame=_.Db(a,13,!1);b.rosterId=_.Db(a,12,
"talk_roster");b.rosterIframeId=_.Db(a,12,"talk_roster");b.rosterIframeIdB=_.Db(a,15,"gtn-roster-iframe-id-b");b.derp=!!_.Db(a,16,!1);c=_.C(a,Gp,14);null!=c&&(b.isCentralRoster=_.Db(c,1,!1),b.useQuasarPanels=_.Db(c,2,!1));c=_.C(a,Dp,10);null!=c&&(b.moleManagerLeftMargin=_.z(c,1),b.moleManagerMiddleMargin=_.z(c,2),b.moleManagerRightMargin=_.z(c,3),b.moleManagerNoMoleAreaMargin=_.z(c,4),b.moleManagerBoundingElementId=_.z(c,5),b.moleWidth=_.z(c,6),b.moleHeight=_.z(c,7),b.minimizedMoleHeight=_.z(c,8));
c=_.C(a,Ep,18);null!=c&&(b.optOutAllowed=_.Db(c,1,!0),d=_.C(c,Fp,3),null!=d&&(b.legacyTalkSignedIn=_.Db(d,1,!0)),c=_.z(c,4),null!=c&&(b.useSpareMole=c));b.uiVersion=2;b.hideStatusMsgs=!0;b.hideRecentConversations=!0;c=new Kp;_.A(c,2,!0);_.A(c,1,!0);_.A(c,3,!1);b.endpointConfig=c;b.ignoreAutomatedRoster=_.Db(a,17,!1);b.conversationId=_.z(a,19);return b},Pp=function(a){switch(a){case 1:return"homepage";case 4:return"Google Translator Toolkit";case 5:return"Google Sites";case 6:return"customersupport";
case 9:return"present";case 15:return"hangout";case 18:return"gmail";case 20:return"docs";case 24:return"docs_hangout";case 22:return"hangout_lite";case 23:return"aChromeExtension";case 25:return"bigtop";case 27:return"ChromeApp";case 36:return"StartPage"}},Rp=function(a,b){if(-1!=a.indexOf("talkgadget.")){var c=_.Ke(a),d=c.a;if(0<=d.indexOf("/u/"))return a;a=d.lastIndexOf("_/");if(0>a||a!=d.length-2)d+="_/";c.a="/u/"+b+d;return c.toString()}return a};
var Sp=function(a,b,c,d,e){_.F.call(this);this.a=a;this.b=d||window.document;this.g=new _.O(this);_.I(this,this.g);var f=_.Ka;d=new _.Q(a.g+a.o);_.Db(a.c,2,!1)||(_.R(d,"ts","0"),_.R(d,"re",a.ec),_.R(d,"ref",a.Yb));_.R(d,"client","sm");_.R(d,"prop",a.Ta);_.R(d,"nav","true");_.R(d,"fid",a.a);a.j&&_.R(d,"debug",a.j);_.R(d,"os",_.fb);_.R(d,"stime",c);a.za&&_.R(d,"hc",a.za);for(c=0;c<kp.length;++c);b=_.Xc(b.a);_.R(d,"xpc",b);_.R(d,"ec",_.Xc(_.D(a.c)));a.m&&_.R(d,"screen",a.m);-1!=f.indexOf("MSIE")&&_.R(d,
"ua",f);a.ya&&_.R(d,"pvt",a.ya);a.jb&&_.R(d,"hsmc","true");_.p(a.W)&&_.R(d,"logl",a.W);b=window.location.href;0>b.indexOf("?rel=1")&&(b=b.split("?"),b[1]=1==b.length?"rel=1":["rel=1&",b[1]].join(""),_.R(d,"href",b.join("?")));b=new _.Q(window.location.href);"false"==fp(b,"uacheck")&&_.R(d,"uacheck",!1);(f=a.Zb)&&_.R(d,"jsmode",f);(f=fp(b,"cssmode"))&&_.R(d,"cssmode",f);(f=fp(b,"convid"))&&_.R(d,"convid",f);if(f=b.g.T("convp"))_.ha(f)||(f=[String(f)]),_.Se(d.g,"convp",f);(f=fp(b,"smexp"))&&_.R(d,"smexp",
f);f=b.g.T("mods");a.$b&&f.push("lazy");e&&(f=_.Aa(f,e));0<f.length&&_.R(d,"mods",f.join(","));if(!a.g||0>a.g.indexOf("/u/"))(e=fp(b,"authuser"))?_.R(d,"authuser",e):null!=a.b&&_.R(d,"authuser",a.b);e=fp(b,"eid");_.Ea(_.Ha(e))||_.R(d,"eid",e);_.Ea(_.Ha(this.a.D))||_.R(d,"eid",this.a.D);null!=this.a.l&&_.R(d,"pos",this.a.l);_.p(a.La)&&_.R(d,"uiv",this.a.La);a.I&&_.R(d,"css",a.I);e=a.locale||fp(b,"hl");null!=e&&_.R(d,"hl",e);_.p(a.Oa)&&_.R(d,"uj",a.Oa);null!=a.P&&_.R(d,"hpc",a.P);null!=a.V&&_.R(d,"hsm",
a.V);null!=a.R&&_.R(d,"hro",a.R);null!=a.N&&_.R(d,"hrc",a.N);null!=a.L&&_.R(d,"hotr",a.L);null!=a.ba&&_.R(d,"pop",a.ba);_.R(d,"pal","1");null!=a.Ma&&_.R(d,"uqp",a.Ma);null!=a.K&&_.R(d,"gooa",a.K);null!=a.M&&_.R(d,"gltsi",a.M);null!=a.Na&&_.R(d,"gusm",a.Na);null!=a.Ja&&_.R(d,"sl",a.Ja);a.kb&&_.R(d,"icr","1");a.gb&&_.R(d,"hpl","1");a.ha&&_.R(d,"hs",a.ha);a.A&&_.R(d,"dc",_.Xc(_.D(a.A)));null!=a.xa&&_.R(d,"molew",a.xa);null!=a.wa&&_.R(d,"moleh",a.wa);null!=a.va&&_.R(d,"mmoleh",a.va);a.hc&&_.R(d,"derp",
"1");a.C&&_.R(d,"fcho",a.C);null!=a.Ka&&_.R(d,"two",a.Ka);null!=a.F&&_.R(d,"convid",a.F);_.R(d,"host","1");_.R(d,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,_.m)()).toString(36));this.c=d.toString()};_.u(Sp,_.F);Sp.prototype.install=function(a,b){Tp(this,a,b,_.ea)};
var Tp=function(a,b,c,d){var e=a.b.getElementById(b);e||(e=a.b.createElement("div"),e.id=b,e.className=a.a.dc,a.b.body.appendChild(e));a=(0,_.t)(function(){var a="";this.a.Xb||(a="height:400px");var b=_.Uc(new _.Tc(this.b),"IFRAME");_.Rc(b,{id:this.a.a,name:this.a.a,"class":"talk_iframe",frameborder:"0",style:a,"aria-hidden":"true",allow:"microphone"});_.Pc("talk_loading_msg",e)||_.Sc(e);e.appendChild(b);var l=this.b.getElementById(this.a.a);_.qe(this.g,l,["load","error"],function(a){l.contentWindow.postMessage("AllowFrame: Chat", "*");d(a)});l.src=this.c.toString();c()},a);window.setTimeout(a,0)};
var Up=function(a){var b=_.Le(_.z(a,2),"/webchat/extension-start");_.z(a,5)&&_.R(b,"e",_.z(a,5));return new _.dc(function(a,d){_.ee(b,function(b){_.ne(b.target)||d();try{var c=b.target;try{var e=c.a?c.a.responseText:""}catch(n){e=""}var l=JSON.parse(e);a(new _.ve(l))}catch(n){d(n.message)}})})};
var Wp=function(){var a=this;_.O.call(this);_.P("Starting ...");this.listen(window,"unload",this.$);this.b=new _.re(JSON.parse((0,window.decodeURI)(window.location.hash.substr(1))));this.a=ip(_.z(this.b,1));_.I(this,this.a);this.g=new _.gf;_.I(this,this.g);dp(Up(this.b).then(function(b){return Vp(a,b)}),function(a){_.P("Failed to start : %s.",a||"")})},Xp;_.u(Wp,_.O);
var Vp=function(a,b){if(!a.G&&(a.a.sendMessage(b),_.z(b,1))){var c=new Cp,d=_.Ke(_.z(a.b,2)),e=d.b;null!=d.c&&(e+=":"+d.c);_.A(c,1,e);_.A(c,2,27);_.A(c,13,!0);_.A(c,17,!0);Hp(c,_.z(b,1));Jp(c,_.z(a.b,4));Ip(c,_.z(a.b,3)||"en");b=Qp(c);var f=new Op(b,b.endpointConfig);f.g=Rp(f.g,f.b);f.C=window.location.origin;f.a="gtn-roster-iframe-id-q";b=lp(f.g,f.a);b=new Sp(f,b,(0,_.m)(),window.document);_.I(a,b);Tp(b,f.gc,function(){},function(){_.mf(a.g,window.document.getElementById(f.a).contentWindow,"31ACFC0_", "google.com");gp(a.g,a.a);gp(a.a,a.g);a.a.sendMessage(new ep)})}};_.oa("default_host._DumpException",function(a){return window.console.error(a.stack)});_.Ef();if(!Xp||Xp.G)Xp=new Wp;

}catch(e){_._DumpException(e)}
/* _GlobalSuffix_ */
}).call(this,this.default_host);
// Google Inc.
